# Generated by Django 3.0.4 on 2020-03-23 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=50)),
                ('Mname', models.CharField(blank=True, max_length=50)),
                ('Lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('Phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone_type', models.CharField(blank=True, max_length=50, null=True)),
                ('Area_code', models.IntegerField(blank=True, null=True)),
                ('Number', models.IntegerField(blank=True, null=True)),
                ('Contact_id', models.ForeignKey(db_column='Contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('Date_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_type', models.CharField(blank=True, max_length=50)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Contact_id', models.ForeignKey(db_column='Contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address_type', models.CharField(max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Zip', models.IntegerField(blank=True, null=True)),
                ('Contact_id', models.ForeignKey(db_column='Contact_id', on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
    ]
