# Generated by Django 3.0.4 on 2020-03-08 02:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=50)),
                ('Mname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('Phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('Phone_type', models.CharField(max_length=50)),
                ('Area_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('Number', models.IntegerField()),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('Date_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_type', models.CharField(max_length=50)),
                ('Date', models.DateTimeField()),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_id', models.AutoField(primary_key=True, serialize=False)),
                ('Address_type', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=100)),
                ('State', localflavor.us.models.USStateField(max_length=2)),
                ('Zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('Contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.Contact')),
            ],
        ),
    ]
