# Generated by Django 3.0.4 on 2020-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_auto_20200321_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Phone_type',
            field=models.CharField(max_length=60),
        ),
    ]
