# Generated by Django 3.0.4 on 2020-03-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_auto_20200321_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date_type',
            field=models.CharField(max_length=40),
        ),
    ]
