# Generated by Django 3.0.4 on 2020-03-22 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_auto_20200322_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Phone_type',
            field=models.CharField(max_length=50),
        ),
    ]
