# Generated by Django 3.0.4 on 2020-03-22 21:05

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_auto_20200322_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Mname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.IntegerField(),
        ),
    ]
