# Generated by Django 3.0.4 on 2020-03-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_auto_20200322_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='Area_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='Phone_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
