# Generated by Django 3.0.4 on 2020-03-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0009_auto_20200322_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
