# Generated by Django 3.0.4 on 2020-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0010_auto_20200322_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Lname',
            field=models.CharField(max_length=50),
        ),
    ]
