# Generated by Django 3.0.4 on 2020-03-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0011_auto_20200322_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='State',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='Street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
